apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: europe-west3-docker.pkg.dev/sleepr-410813/notifications/production
        name: notifications
        env: 
          - name: PORT
            value: '3004'
          - name: GOOGLE_CLIENT_ID
            value: 591024560667-12uiuosssp43eu8ri1e76d7td7g1o8o3.apps.googleusercontent.com
          - name: SMTP_USER
            value: sleeprapplication@gmail.com
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
        ports:
          - containerPort: 3004
