apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication
  name: auth-tcp
spec:
  ports:
  - name: "http"
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: authentication
  type: ClusterIP
