services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  
  mongo:
    image: mongo

  reservations:
    image: "" # TODO: Insert production image
    ports: 
      - '3000:3000'
    env_file:
      - ../apps/reservations/.env
      
  auth:
    image: "" # TODO: Insert production image
    ports: 
      - '3001:3001'
    env_file:
      - ../apps/auth/.env

  payments:
    image: "" # TODO: Insert production image
    ports: 
      - '3003:3003'
    env_file:
      - ../apps/payments/.env

  notifications:
    image: "" # TODO: Insert production image
    ports: 
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env