apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: europe-west3-docker.pkg.dev/sleepr-410813/reservations/production
        name: reservations
        env: 
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: PORT
            value: '3000'
          - name: AUTH_HOST
            value: auth-tcp
          - name: AUTH_PORT
            value: '3002'
          - name: PAYMENTS_HOST
            value: payments 
          - name: PAYMENTS_PORT
            value: '3003'
        ports: 
          - containerPort: 3000
